apiVersion: v1
kind: Secret
metadata:
  name: catalog-service-secret
  namespace: ecom-app
type: Opaque
stringData:
  MYSQL_DSN: "catalog-user:CHANGE_ME@tcp(mysql.ecom-app.svc.cluster.local:3306)/catalog-db?parseTime=true&multiStatements=true"
  REDIS_PASSWORD: ""
  ADMIN_TOKEN: "CHANGE_ME_ADMIN_TOKEN"